DROP TABLE IF EXISTS USERS_TABLE;
CREATE TABLE USERS_TABLE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
);

INSERT INTO USERS_TABLE (NOME, PODER)
VALUES ('Flash', 'Velocidade');